"""sync remaining missing columns

Revision ID: 7106bbc1c756
Revises: 845d990f0099
Create Date: 2026-08-27 13:32:43.087913

NOTE: Made idempotent for the same reason as 845d990f0099 — this migration
duplicates several columns (user_login_history.latitude/longitude/is_vpn/
is_unusual/risk_score) that 845d990f0099 already creates, so on a database
where that migration has already run, this one would otherwise fail with
DuplicateColumnError. Every op call is wrapped in _safe(), which runs it
inside its own SAVEPOINT and tolerates "already exists" / "does not exist"
failures without poisoning the rest of the migration's transaction — see
the longer explanation in 845d990f0099's docstring for why a plain
try/except alone isn't enough here (Postgres aborts the whole enclosing
transaction on any failed statement; a savepoint is what lets us recover
from just one statement and keep going).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import ProgrammingError

# revision identifiers, used by Alembic.
revision: str = '7106bbc1c756'
down_revision: Union[str, None] = '845d990f0099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _safe(label: str, fn) -> None:
    """
    Runs an Alembic op call inside its own SAVEPOINT, tolerating "already
    exists" / "does not exist" failures. Anything else re-raises after
    rolling back to the savepoint. See 845d990f0099 for the full rationale.
    """
    bind = op.get_bind()
    savepoint = bind.begin_nested()  # SAVEPOINT — rollback here doesn't touch the outer transaction
    try:
        fn()
    except ProgrammingError as e:
        savepoint.rollback()
        msg = str(getattr(e, "orig", None) or e).lower()
        if "already exists" in msg or "does not exist" in msg:
            print(f"⚠️  Skipping '{label}' — already in desired state ({msg.splitlines()[0]})")
        else:
            raise
    else:
        savepoint.commit()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### (now wrapped in _safe)
    _safe("applications.case_origin nullable=True",
          lambda: op.alter_column('applications', 'case_origin',
                                   existing_type=postgresql.ENUM('employer_sponsored', 'self_petition', 'lawyer_initiated', name='case_origin_enum'),
                                   nullable=True))

    _safe("employee_forms.review_note",
          lambda: op.add_column('employee_forms', sa.Column('review_note', sa.Text(), nullable=True)))
    _safe("employee_forms.reviewed_by",
          lambda: op.add_column('employee_forms', sa.Column('reviewed_by', sa.UUID(), nullable=True)))
    _safe("employee_forms.reviewed_at",
          lambda: op.add_column('employee_forms', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True)))
    _safe("employee_forms.current_version",
          lambda: op.add_column('employee_forms', sa.Column('current_version', sa.Integer(), server_default='1', nullable=False)))
    _safe("employee_forms.last_action_by",
          lambda: op.add_column('employee_forms', sa.Column('last_action_by', sa.UUID(), nullable=True)))
    _safe("employee_forms.last_action_by_role",
          lambda: op.add_column('employee_forms', sa.Column('last_action_by_role', sa.String(length=20), nullable=True)))
    _safe("employee_forms.last_action_at",
          lambda: op.add_column('employee_forms', sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True)))
    _safe("fk employee_forms.last_action_by -> users",
          lambda: op.create_foreign_key(None, 'employee_forms', 'users', ['last_action_by'], ['id']))
    _safe("fk employee_forms.reviewed_by -> users",
          lambda: op.create_foreign_key(None, 'employee_forms', 'users', ['reviewed_by'], ['id']))

    _safe("user_login_history.latitude",
          lambda: op.add_column('user_login_history', sa.Column('latitude', sa.Float(), nullable=True)))
    _safe("user_login_history.longitude",
          lambda: op.add_column('user_login_history', sa.Column('longitude', sa.Float(), nullable=True)))
    _safe("user_login_history.is_vpn",
          lambda: op.add_column('user_login_history', sa.Column('is_vpn', sa.Boolean(), server_default='false', nullable=False)))
    _safe("user_login_history.is_unusual",
          lambda: op.add_column('user_login_history', sa.Column('is_unusual', sa.Boolean(), server_default='false', nullable=False)))
    _safe("user_login_history.risk_score",
          lambda: op.add_column('user_login_history', sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### (now wrapped in _safe)
    _safe("drop user_login_history.risk_score",
          lambda: op.drop_column('user_login_history', 'risk_score'))
    _safe("drop user_login_history.is_unusual",
          lambda: op.drop_column('user_login_history', 'is_unusual'))
    _safe("drop user_login_history.is_vpn",
          lambda: op.drop_column('user_login_history', 'is_vpn'))
    _safe("drop user_login_history.longitude",
          lambda: op.drop_column('user_login_history', 'longitude'))
    _safe("drop user_login_history.latitude",
          lambda: op.drop_column('user_login_history', 'latitude'))

    _safe("drop fk employee_forms -> users (#1)",
          lambda: op.drop_constraint(None, 'employee_forms', type_='foreignkey'))
    _safe("drop fk employee_forms -> users (#2)",
          lambda: op.drop_constraint(None, 'employee_forms', type_='foreignkey'))
    _safe("drop employee_forms.last_action_at",
          lambda: op.drop_column('employee_forms', 'last_action_at'))
    _safe("drop employee_forms.last_action_by_role",
          lambda: op.drop_column('employee_forms', 'last_action_by_role'))
    _safe("drop employee_forms.last_action_by",
          lambda: op.drop_column('employee_forms', 'last_action_by'))
    _safe("drop employee_forms.current_version",
          lambda: op.drop_column('employee_forms', 'current_version'))
    _safe("drop employee_forms.reviewed_at",
          lambda: op.drop_column('employee_forms', 'reviewed_at'))
    _safe("drop employee_forms.reviewed_by",
          lambda: op.drop_column('employee_forms', 'reviewed_by'))
    _safe("drop employee_forms.review_note",
          lambda: op.drop_column('employee_forms', 'review_note'))

    _safe("applications.case_origin nullable=False",
          lambda: op.alter_column('applications', 'case_origin',
                                   existing_type=postgresql.ENUM('employer_sponsored', 'self_petition', 'lawyer_initiated', name='case_origin_enum'),
                                   nullable=False))
    # ### end Alembic commands ###