"""sync remaining missing columns

Revision ID: 7106bbc1c756
Revises: 845d990f0099
Create Date: 2026-08-27 13:32:43.087913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7106bbc1c756'
down_revision: Union[str, None] = '845d990f0099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'case_origin',
        existing_type=postgresql.ENUM('employer_sponsored', 'self_petition', 'lawyer_initiated', name='case_origin_enum'),
        nullable=True)
    op.add_column('employee_forms', sa.Column('review_note', sa.Text(), nullable=True))
    op.add_column('employee_forms', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('employee_forms', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employee_forms', sa.Column('current_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('employee_forms', sa.Column('last_action_by', sa.UUID(), nullable=True))
    op.add_column('employee_forms', sa.Column('last_action_by_role', sa.String(length=20), nullable=True))
    op.add_column('employee_forms', sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'employee_forms', 'users', ['last_action_by'], ['id'])
    op.create_foreign_key(None, 'employee_forms', 'users', ['reviewed_by'], ['id'])
    op.add_column('user_login_history', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user_login_history', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('user_login_history', sa.Column('is_vpn', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_login_history', sa.Column('is_unusual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_login_history', sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login_history', 'risk_score')
    op.drop_column('user_login_history', 'is_unusual')
    op.drop_column('user_login_history', 'is_vpn')
    op.drop_column('user_login_history', 'longitude')
    op.drop_column('user_login_history', 'latitude')
    op.drop_constraint(None, 'employee_forms', type_='foreignkey')
    op.drop_constraint(None, 'employee_forms', type_='foreignkey')
    op.drop_column('employee_forms', 'last_action_at')
    op.drop_column('employee_forms', 'last_action_by_role')
    op.drop_column('employee_forms', 'last_action_by')
    op.drop_column('employee_forms', 'current_version')
    op.drop_column('employee_forms', 'reviewed_at')
    op.drop_column('employee_forms', 'reviewed_by')
    op.drop_column('employee_forms', 'review_note')
    op.alter_column('applications', 'case_origin',
        existing_type=postgresql.ENUM('employer_sponsored', 'self_petition', 'lawyer_initiated', name='case_origin_enum'),
        nullable=False)
    # ### end Alembic commands ###