"""sync missing columns from replace_doc merge

Revision ID: 845d990f0099
Revises: 
Create Date: 2026-08-25 19:14:13.447319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845d990f0099'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_tasks', sa.Column('is_renewal', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('application_tasks', sa.Column('renewal_of_document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'application_tasks', 'documents', ['renewal_of_document_id'], ['id'])
    op.add_column('applications', sa.Column('priority_date', sa.Date(), nullable=True))

    # case_origin: VARCHAR -> new enum type. Postgres needs the type created
    # first, then an explicit USING cast — it cannot infer this automatically.
    case_origin_enum = sa.Enum('employer_sponsored', 'self_petition', 'lawyer_initiated', name='case_origin_enum')
    case_origin_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE applications ALTER COLUMN case_origin TYPE case_origin_enum USING case_origin::text::case_origin_enum")
    op.alter_column('applications', 'case_origin', nullable=False)

    # case_pipeline_stage: same treatment, stays nullable.
    case_pipeline_stage_enum = sa.Enum('intake', 'filed', 'rfe', 'decision', name='case_pipeline_stage_enum')
    case_pipeline_stage_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE applications ALTER COLUMN case_pipeline_stage TYPE case_pipeline_stage_enum USING case_pipeline_stage::text::case_pipeline_stage_enum")

    op.create_index(op.f('ix_applications_intake_accepted_at'), 'applications', ['intake_accepted_at'], unique=False)
    op.create_index(op.f('ix_applications_receipt_number'), 'applications', ['receipt_number'], unique=False)
    op.create_foreign_key(None, 'applications', 'users', ['intake_accepted_by'], ['id'])
    op.create_index(op.f('ix_attorney_profiles_firm_id'), 'attorney_profiles', ['firm_id'], unique=False)
    op.create_foreign_key(None, 'attorney_profiles', 'law_firms', ['firm_id'], ['id'])
    op.add_column('client_intake_sessions', sa.Column('review_status', sa.Enum('not_submitted', 'pending_review', 'changes_requested', 'accepted', name='intake_review_status_enum'), nullable=False))
    op.add_column('client_intake_sessions', sa.Column('review_note', sa.Text(), nullable=True))
    op.add_column('client_intake_sessions', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('client_intake_sessions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('client_intake_sessions', sa.Column('revision_count', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client_intake_sessions', 'users', ['reviewed_by'], ['id'])
    op.add_column('consultation_bookings', sa.Column('application_id', sa.UUID(), nullable=True))
    op.add_column('consultation_bookings', sa.Column('zoho_session_key', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_consultation_bookings_application_id'), 'consultation_bookings', ['application_id'], unique=False)
    op.create_foreign_key(None, 'consultation_bookings', 'applications', ['application_id'], ['id'])
    op.add_column('documents', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('activates_on', sa.Date(), nullable=True))
    op.drop_constraint('uq_employer_employee_pair', 'employer_employees', type_='unique')
    op.add_column('employer_invitations', sa.Column('invited_passport_hash', sa.String(length=64), nullable=True))
    op.add_column('intake_immigration_history', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('intake_immigration_history', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('intake_immigration_history', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('intake_immigration_history', sa.Column('job_title', sa.String(length=200), nullable=True))
    op.add_column('intake_immigration_history', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('intake_immigration_history', sa.Column('annual_salary', sa.String(length=30), nullable=True))
    op.add_column('intake_immigration_history', sa.Column('visa_type_code', sa.String(length=30), nullable=True))
    op.add_column('user_login_history', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user_login_history', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('user_login_history', sa.Column('is_vpn', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_login_history', sa.Column('is_unusual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_login_history', sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login_history', 'risk_score')
    op.drop_column('user_login_history', 'is_unusual')
    op.drop_column('user_login_history', 'is_vpn')
    op.drop_column('user_login_history', 'longitude')
    op.drop_column('user_login_history', 'latitude')
    op.drop_column('intake_immigration_history', 'visa_type_code')
    op.drop_column('intake_immigration_history', 'annual_salary')
    op.drop_column('intake_immigration_history', 'start_date')
    op.drop_column('intake_immigration_history', 'job_title')
    op.drop_column('intake_immigration_history', 'company_name')
    op.drop_column('intake_immigration_history', 'is_student')
    op.drop_column('intake_immigration_history', 'phone')
    op.drop_column('employer_invitations', 'invited_passport_hash')
    op.create_unique_constraint('uq_employer_employee_pair', 'employer_employees', ['employer_id', 'employee_id'])
    op.drop_column('documents', 'activates_on')
    op.drop_column('documents', 'expiry_date')
    op.drop_constraint(None, 'consultation_bookings', type_='foreignkey')
    op.drop_index(op.f('ix_consultation_bookings_application_id'), table_name='consultation_bookings')
    op.drop_column('consultation_bookings', 'zoho_session_key')
    op.drop_column('consultation_bookings', 'application_id')
    op.drop_constraint(None, 'client_intake_sessions', type_='foreignkey')
    op.drop_column('client_intake_sessions', 'revision_count')
    op.drop_column('client_intake_sessions', 'reviewed_at')
    op.drop_column('client_intake_sessions', 'reviewed_by')
    op.drop_column('client_intake_sessions', 'review_note')
    op.drop_column('client_intake_sessions', 'review_status')
    op.drop_constraint(None, 'attorney_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_attorney_profiles_firm_id'), table_name='attorney_profiles')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_receipt_number'), table_name='applications')
    op.drop_index(op.f('ix_applications_intake_accepted_at'), table_name='applications')
    op.alter_column('applications', 'case_pipeline_stage',
               existing_type=sa.Enum('intake', 'filed', 'rfe', 'decision', name='case_pipeline_stage_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('applications', 'case_origin',
               existing_type=sa.Enum('employer_sponsored', 'self_petition', 'lawyer_initiated', name='case_origin_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('applications', 'priority_date')
    op.drop_constraint(None, 'application_tasks', type_='foreignkey')
    op.drop_column('application_tasks', 'renewal_of_document_id')
    op.drop_column('application_tasks', 'is_renewal')
    # ### end Alembic commands ###
