"""sync missing columns from replace_doc merge

Revision ID: 845d990f0099
Revises: 
Create Date: 2026-08-25 19:14:13.447319

NOTE: This migration was made idempotent after discovering the database had
already drifted from Alembic's history (some of these columns/objects were
already present, causing DuplicateColumnError / DuplicateObject errors
partway through a plain re-run). Every add_column / create_index /
create_foreign_key / drop_constraint call below is now wrapped in _safe(),
which runs the statement inside its own SAVEPOINT and tolerates "already
exists" / "does not exist" failures (the two shapes this reconciliation
migration can legitimately hit on a drifted database) by rolling back just
that savepoint and continuing — not the whole migration transaction.
Anything else (a real, unexpected DB error) still raises normally, and
still rolls back the whole migration as usual.

IMPORTANT: a plain try/except around each op call is NOT enough on its
own — Postgres aborts the entire enclosing transaction the moment any
statement fails, and rejects every subsequent statement with
InFailedSQLTransactionError until an explicit ROLLBACK happens, even ones
that have nothing to do with the original error. _safe() issues that
rollback by wrapping each statement in its own SAVEPOINT (a nested
transaction) via begin_nested() — a failure there only rolls back to that
savepoint, leaving the outer migration transaction healthy so the next
statement can still run normally.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import ProgrammingError


# revision identifiers, used by Alembic.
revision: str = '845d990f0099'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _safe(label: str, fn) -> None:
    """
    Runs an Alembic op call inside its own SAVEPOINT, tolerating "already
    exists" / "does not exist" failures (the two shapes this reconciliation
    migration can legitimately hit on a drifted database). Anything else
    re-raises after rolling back to the savepoint — this is not a blanket
    try/except, only a targeted one for the specific class of error this
    migration exists to survive.
    """
    bind = op.get_bind()
    savepoint = bind.begin_nested()  # SAVEPOINT — rollback here doesn't touch the outer transaction
    try:
        fn()
    except ProgrammingError as e:
        savepoint.rollback()
        msg = str(getattr(e, "orig", None) or e).lower()
        if "already exists" in msg or "does not exist" in msg:
            print(f"⚠️  Skipping '{label}' — already in desired state ({msg.splitlines()[0]})")
        else:
            raise
    else:
        savepoint.commit()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### (now wrapped in _safe)
    _safe("application_tasks.renewal_of_document_id",
          lambda: op.add_column('application_tasks', sa.Column('renewal_of_document_id', sa.UUID(), nullable=True)))
    _safe("fk application_tasks.renewal_of_document_id -> documents",
          lambda: op.create_foreign_key(None, 'application_tasks', 'documents', ['renewal_of_document_id'], ['id']))
    _safe("applications.priority_date",
          lambda: op.add_column('applications', sa.Column('priority_date', sa.Date(), nullable=True)))

    # case_origin: VARCHAR -> new enum type. Postgres needs the type created
    # first, then an explicit USING cast — it cannot infer this automatically.
    # Enum.create(..., checkfirst=True) is already idempotent by itself.
    case_origin_enum = sa.Enum('employer_sponsored', 'self_petition', 'lawyer_initiated', name='case_origin_enum')
    case_origin_enum.create(op.get_bind(), checkfirst=True)
    _safe("applications.case_origin -> case_origin_enum",
          lambda: op.execute("ALTER TABLE applications ALTER COLUMN case_origin TYPE case_origin_enum USING case_origin::text::case_origin_enum"))
    _safe("applications.case_origin NOT NULL",
          lambda: op.alter_column('applications', 'case_origin', nullable=False))

    # case_pipeline_stage: same treatment, stays nullable.
    case_pipeline_stage_enum = sa.Enum('intake', 'filed', 'rfe', 'decision', name='case_pipeline_stage_enum')
    case_pipeline_stage_enum.create(op.get_bind(), checkfirst=True)
    _safe("applications.case_pipeline_stage -> case_pipeline_stage_enum",
          lambda: op.execute("ALTER TABLE applications ALTER COLUMN case_pipeline_stage TYPE case_pipeline_stage_enum USING case_pipeline_stage::text::case_pipeline_stage_enum"))

    _safe("ix_applications_intake_accepted_at",
          lambda: op.create_index(op.f('ix_applications_intake_accepted_at'), 'applications', ['intake_accepted_at'], unique=False))
    _safe("ix_applications_receipt_number",
          lambda: op.create_index(op.f('ix_applications_receipt_number'), 'applications', ['receipt_number'], unique=False))
    _safe("fk applications.intake_accepted_by -> users",
          lambda: op.create_foreign_key(None, 'applications', 'users', ['intake_accepted_by'], ['id']))
    _safe("ix_attorney_profiles_firm_id",
          lambda: op.create_index(op.f('ix_attorney_profiles_firm_id'), 'attorney_profiles', ['firm_id'], unique=False))
    _safe("fk attorney_profiles.firm_id -> law_firms",
          lambda: op.create_foreign_key(None, 'attorney_profiles', 'law_firms', ['firm_id'], ['id']))

    _safe("client_intake_sessions.review_status",
          lambda: op.add_column('client_intake_sessions', sa.Column('review_status', sa.Enum('not_submitted', 'pending_review', 'changes_requested', 'accepted', name='intake_review_status_enum'), nullable=False)))
    _safe("client_intake_sessions.review_note",
          lambda: op.add_column('client_intake_sessions', sa.Column('review_note', sa.Text(), nullable=True)))
    _safe("client_intake_sessions.reviewed_by",
          lambda: op.add_column('client_intake_sessions', sa.Column('reviewed_by', sa.UUID(), nullable=True)))
    _safe("client_intake_sessions.reviewed_at",
          lambda: op.add_column('client_intake_sessions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True)))
    _safe("client_intake_sessions.revision_count",
          lambda: op.add_column('client_intake_sessions', sa.Column('revision_count', sa.Integer(), nullable=False)))
    _safe("fk client_intake_sessions.reviewed_by -> users",
          lambda: op.create_foreign_key(None, 'client_intake_sessions', 'users', ['reviewed_by'], ['id']))

    _safe("consultation_bookings.application_id",
          lambda: op.add_column('consultation_bookings', sa.Column('application_id', sa.UUID(), nullable=True)))
    _safe("consultation_bookings.zoho_session_key",
          lambda: op.add_column('consultation_bookings', sa.Column('zoho_session_key', sa.String(length=200), nullable=True)))
    _safe("ix_consultation_bookings_application_id",
          lambda: op.create_index(op.f('ix_consultation_bookings_application_id'), 'consultation_bookings', ['application_id'], unique=False))
    _safe("fk consultation_bookings.application_id -> applications",
          lambda: op.create_foreign_key(None, 'consultation_bookings', 'applications', ['application_id'], ['id']))

    _safe("documents.expiry_date",
          lambda: op.add_column('documents', sa.Column('expiry_date', sa.Date(), nullable=True)))
    _safe("documents.activates_on",
          lambda: op.add_column('documents', sa.Column('activates_on', sa.Date(), nullable=True)))

    _safe("drop uq_employer_employee_pair",
          lambda: op.drop_constraint('uq_employer_employee_pair', 'employer_employees', type_='unique'))

    _safe("employer_invitations.invited_passport_hash",
          lambda: op.add_column('employer_invitations', sa.Column('invited_passport_hash', sa.String(length=64), nullable=True)))

    _safe("intake_immigration_history.phone",
          lambda: op.add_column('intake_immigration_history', sa.Column('phone', sa.String(length=30), nullable=True)))
    _safe("intake_immigration_history.is_student",
          lambda: op.add_column('intake_immigration_history', sa.Column('is_student', sa.Boolean(), nullable=True)))
    _safe("intake_immigration_history.company_name",
          lambda: op.add_column('intake_immigration_history', sa.Column('company_name', sa.String(length=200), nullable=True)))
    _safe("intake_immigration_history.job_title",
          lambda: op.add_column('intake_immigration_history', sa.Column('job_title', sa.String(length=200), nullable=True)))
    _safe("intake_immigration_history.start_date",
          lambda: op.add_column('intake_immigration_history', sa.Column('start_date', sa.Date(), nullable=True)))
    _safe("intake_immigration_history.annual_salary",
          lambda: op.add_column('intake_immigration_history', sa.Column('annual_salary', sa.String(length=30), nullable=True)))
    _safe("intake_immigration_history.visa_type_code",
          lambda: op.add_column('intake_immigration_history', sa.Column('visa_type_code', sa.String(length=30), nullable=True)))

    _safe("user_login_history.latitude",
          lambda: op.add_column('user_login_history', sa.Column('latitude', sa.Float(), nullable=True)))
    _safe("user_login_history.longitude",
          lambda: op.add_column('user_login_history', sa.Column('longitude', sa.Float(), nullable=True)))
    _safe("user_login_history.is_vpn",
          lambda: op.add_column('user_login_history', sa.Column('is_vpn', sa.Boolean(), server_default='false', nullable=False)))
    _safe("user_login_history.is_unusual",
          lambda: op.add_column('user_login_history', sa.Column('is_unusual', sa.Boolean(), server_default='false', nullable=False)))
    _safe("user_login_history.risk_score",
          lambda: op.add_column('user_login_history', sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False)))

    # Already idempotent via raw SQL IF NOT EXISTS — left as-is.
    op.execute("ALTER TABLE application_tasks ADD COLUMN IF NOT EXISTS is_renewal BOOLEAN DEFAULT 'false' NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### (now wrapped in _safe)
    _safe("drop user_login_history.risk_score",
          lambda: op.drop_column('user_login_history', 'risk_score'))
    _safe("drop user_login_history.is_unusual",
          lambda: op.drop_column('user_login_history', 'is_unusual'))
    _safe("drop user_login_history.is_vpn",
          lambda: op.drop_column('user_login_history', 'is_vpn'))
    _safe("drop user_login_history.longitude",
          lambda: op.drop_column('user_login_history', 'longitude'))
    _safe("drop user_login_history.latitude",
          lambda: op.drop_column('user_login_history', 'latitude'))

    _safe("drop intake_immigration_history.visa_type_code",
          lambda: op.drop_column('intake_immigration_history', 'visa_type_code'))
    _safe("drop intake_immigration_history.annual_salary",
          lambda: op.drop_column('intake_immigration_history', 'annual_salary'))
    _safe("drop intake_immigration_history.start_date",
          lambda: op.drop_column('intake_immigration_history', 'start_date'))
    _safe("drop intake_immigration_history.job_title",
          lambda: op.drop_column('intake_immigration_history', 'job_title'))
    _safe("drop intake_immigration_history.company_name",
          lambda: op.drop_column('intake_immigration_history', 'company_name'))
    _safe("drop intake_immigration_history.is_student",
          lambda: op.drop_column('intake_immigration_history', 'is_student'))
    _safe("drop intake_immigration_history.phone",
          lambda: op.drop_column('intake_immigration_history', 'phone'))

    _safe("drop employer_invitations.invited_passport_hash",
          lambda: op.drop_column('employer_invitations', 'invited_passport_hash'))
    _safe("recreate uq_employer_employee_pair",
          lambda: op.create_unique_constraint('uq_employer_employee_pair', 'employer_employees', ['employer_id', 'employee_id']))

    _safe("drop documents.activates_on",
          lambda: op.drop_column('documents', 'activates_on'))
    _safe("drop documents.expiry_date",
          lambda: op.drop_column('documents', 'expiry_date'))

    _safe("drop fk consultation_bookings -> applications",
          lambda: op.drop_constraint(None, 'consultation_bookings', type_='foreignkey'))
    _safe("drop ix_consultation_bookings_application_id",
          lambda: op.drop_index(op.f('ix_consultation_bookings_application_id'), table_name='consultation_bookings'))
    _safe("drop consultation_bookings.zoho_session_key",
          lambda: op.drop_column('consultation_bookings', 'zoho_session_key'))
    _safe("drop consultation_bookings.application_id",
          lambda: op.drop_column('consultation_bookings', 'application_id'))

    _safe("drop fk client_intake_sessions -> users",
          lambda: op.drop_constraint(None, 'client_intake_sessions', type_='foreignkey'))
    _safe("drop client_intake_sessions.revision_count",
          lambda: op.drop_column('client_intake_sessions', 'revision_count'))
    _safe("drop client_intake_sessions.reviewed_at",
          lambda: op.drop_column('client_intake_sessions', 'reviewed_at'))
    _safe("drop client_intake_sessions.reviewed_by",
          lambda: op.drop_column('client_intake_sessions', 'reviewed_by'))
    _safe("drop client_intake_sessions.review_note",
          lambda: op.drop_column('client_intake_sessions', 'review_note'))
    _safe("drop client_intake_sessions.review_status",
          lambda: op.drop_column('client_intake_sessions', 'review_status'))

    _safe("drop fk attorney_profiles -> law_firms",
          lambda: op.drop_constraint(None, 'attorney_profiles', type_='foreignkey'))
    _safe("drop ix_attorney_profiles_firm_id",
          lambda: op.drop_index(op.f('ix_attorney_profiles_firm_id'), table_name='attorney_profiles'))

    _safe("drop fk applications -> users (intake_accepted_by)",
          lambda: op.drop_constraint(None, 'applications', type_='foreignkey'))
    _safe("drop ix_applications_receipt_number",
          lambda: op.drop_index(op.f('ix_applications_receipt_number'), table_name='applications'))
    _safe("drop ix_applications_intake_accepted_at",
          lambda: op.drop_index(op.f('ix_applications_intake_accepted_at'), table_name='applications'))

    _safe("revert applications.case_pipeline_stage to VARCHAR",
          lambda: op.alter_column('applications', 'case_pipeline_stage',
                                   existing_type=sa.Enum('intake', 'filed', 'rfe', 'decision', name='case_pipeline_stage_enum'),
                                   type_=sa.VARCHAR(),
                                   existing_nullable=True))
    _safe("revert applications.case_origin to VARCHAR",
          lambda: op.alter_column('applications', 'case_origin',
                                   existing_type=sa.Enum('employer_sponsored', 'self_petition', 'lawyer_initiated', name='case_origin_enum'),
                                   type_=sa.VARCHAR(),
                                   nullable=True))

    _safe("drop applications.priority_date",
          lambda: op.drop_column('applications', 'priority_date'))
    _safe("drop fk application_tasks -> documents (renewal_of_document_id)",
          lambda: op.drop_constraint(None, 'application_tasks', type_='foreignkey'))
    _safe("drop application_tasks.renewal_of_document_id",
          lambda: op.drop_column('application_tasks', 'renewal_of_document_id'))
    _safe("drop application_tasks.is_renewal",
          lambda: op.drop_column('application_tasks', 'is_renewal'))
    # ### end Alembic commands ###